#!/usr/bin/env node

/**
 * Validate the small PE launchers generated by generate-pe-exe.cjs.
 * No Windows SDK or third-party package is required, so this can run in CI.
 */

const fs = require("node:fs");
const path = require("node:path");

const rootDir = path.resolve(__dirname, "..");
const expected = {
  "bsat-studio.exe": "cmd.exe /k start-server.bat",
  "bsat-compiler.exe": "cmd.exe /k compile-and-run.bat",
  "bsat-supervisor.exe": "cmd.exe /k dev-watch.bat",
};
const locations = [rootDir, path.join(rootDir, "dist-exe"), path.join(rootDir, "public")];

let errors = 0;
let warnings = 0;

function error(file, message) {
  errors += 1;
  console.error(`[ERROR] ${file}: ${message}`);
}

function warning(file, message) {
  warnings += 1;
  console.warn(`[WARN]  ${file}: ${message}`);
}

function readAscii(buffer, offset, length) {
  return buffer.toString("ascii", offset, offset + length).replace(/\0+$/, "");
}

function validate(filePath, filename) {
  const label = path.relative(rootDir, filePath) || filename;
  if (!fs.existsSync(filePath)) {
    error(label, "file is missing");
    return;
  }

  const buffer = fs.readFileSync(filePath);
  if (buffer.length < 0x200) {
    error(label, `file is too small to be a PE image (${buffer.length} bytes)`);
    return;
  }

  const readU16 = (offset) => buffer.readUInt16LE(offset);
  const readU32 = (offset) => buffer.readUInt32LE(offset);
  const readU64 = (offset) => buffer.readBigUInt64LE(offset);
  const peOffset = readU32(0x3c);

  if (readAscii(buffer, 0, 2) !== "MZ") {
    error(label, "missing DOS MZ signature");
    return;
  }
  if (peOffset + 4 + 20 > buffer.length || readAscii(buffer, peOffset, 4) !== "PE") {
    error(label, "missing or truncated PE signature");
    return;
  }

  const coff = peOffset + 4;
  const machine = readU16(coff);
  const sectionCount = readU16(coff + 2);
  const optionalSize = readU16(coff + 16);
  const optional = coff + 20;
  const sectionTable = optional + optionalSize;

  if (machine !== 0x8664) error(label, `expected AMD64 machine (0x8664), found 0x${machine.toString(16)}`);
  if (sectionCount < 2) error(label, `expected at least two sections, found ${sectionCount}`);
  if (optionalSize !== 240) error(label, `expected a 240-byte PE32+ optional header, found ${optionalSize}`);
  if (optional + 240 > buffer.length || sectionTable + sectionCount * 40 > buffer.length) {
    error(label, "section table or optional header is truncated");
    return;
  }

  const magic = readU16(optional);
  const entryRva = readU32(optional + 16);
  const imageBase = readU64(optional + 24);
  const sectionAlignment = readU32(optional + 32);
  const fileAlignment = readU32(optional + 36);
  const sizeOfHeaders = readU32(optional + 60);
  const subsystem = readU16(optional + 68);
  const dllCharacteristics = readU16(optional + 70);
  const importRva = readU32(optional + 120);
  const importSize = readU32(optional + 124);

  if (magic !== 0x20b) error(label, `expected PE32+ optional header (0x20b), found 0x${magic.toString(16)}`);
  if (entryRva === 0) error(label, "entry point is zero");
  if (imageBase !== 0x140000000n) warning(label, `unexpected image base 0x${imageBase.toString(16)}`);
  if (sectionAlignment !== 0x1000) error(label, `unexpected section alignment 0x${sectionAlignment.toString(16)}`);
  if (fileAlignment !== 0x200) error(label, `unexpected file alignment 0x${fileAlignment.toString(16)}`);
  if (sizeOfHeaders % fileAlignment !== 0) error(label, "header size is not file-alignment aligned");
  if (subsystem !== 3) error(label, `expected Windows console subsystem (3), found ${subsystem}`);
  if ((dllCharacteristics & 0x40) !== 0) warning(label, "dynamic-base is set but this minimal launcher has no relocation table");
  if (importRva === 0 || importSize === 0) error(label, "import directory is missing");

  let entryInSection = false;
  let importInSection = false;
  for (let i = 0; i < sectionCount; i += 1) {
    const section = sectionTable + i * 40;
    const name = readAscii(buffer, section, 8);
    const virtualSize = readU32(section + 8);
    const virtualAddress = readU32(section + 12);
    const rawSize = readU32(section + 16);
    const rawPointer = readU32(section + 20);
    const endRva = virtualAddress + Math.max(virtualSize, rawSize);
    if (entryRva >= virtualAddress && entryRva < endRva) entryInSection = true;
    if (importRva >= virtualAddress && importRva < endRva) importInSection = true;
    if (rawPointer + rawSize > buffer.length) error(label, `${name} section extends beyond file bounds`);
    if (!rawPointer || !rawSize) warning(label, `${name} section has no raw file data`);
  }
  if (!entryInSection) error(label, `entry point RVA 0x${entryRva.toString(16)} is outside all sections`);
  if (!importInSection) error(label, `import RVA 0x${importRva.toString(16)} is outside all sections`);

  const content = buffer.toString("ascii");
  const command = expected[filename];
  if (!content.includes(command)) error(label, `expected launcher command is missing: ${command}`);
  const textBytes = buffer.subarray(0x400, 0x600);
  const expectedFirstCall = Buffer.from([0xff, 0x15, 0x3a, 0x10, 0x00, 0x00]);
  const expectedExitCall = Buffer.from([0xff, 0x15, 0x38, 0x10, 0x00, 0x00]);
  const firstCallOffset = textBytes.indexOf(expectedFirstCall);
  const exitCallOffset = textBytes.indexOf(expectedExitCall);
  if (firstCallOffset < 0) error(label, "WinExec RIP-relative IAT call is malformed");
  if (exitCallOffset < 0) error(label, "ExitProcess RIP-relative IAT call is malformed");
  const wrongExitCall = Buffer.from([0xff, 0x15, 0x3a, 0x10, 0x00, 0x00]);
  if (textBytes.indexOf(wrongExitCall) >= 0 && exitCallOffset < 0) error(label, "found legacy broken ExitProcess displacement");

  if (!content.includes("KERNEL32.dll") || !content.includes("WinExec") || !content.includes("ExitProcess")) {
    error(label, "required Kernel32 imports are incomplete");
  }

  console.log(`[OK] ${label}: ${buffer.length} bytes, PE32+ AMD64, entry RVA 0x${entryRva.toString(16)}, command: ${command}`);
}

for (const directory of locations) {
  for (const filename of Object.keys(expected)) {
    validate(path.join(directory, filename), filename);
  }
}

if (warnings === 0) console.log("[OK] No executable warnings detected.");
else console.warn(`[WARN] ${warnings} executable warning(s) detected.`);
if (errors > 0) {
  console.error(`[FAIL] ${errors} executable error(s) detected.`);
  process.exitCode = 1;
} else {
  console.log("[PASS] All executable artifacts passed validation.");
}
